# Generated by Django 4.2.1 on 2023-05-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                ("imagen", models.CharField(max_length=1000)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("gender", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("year", models.IntegerField(max_length=20)),
                ("imagen", models.CharField(max_length=1000)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("actors", models.ManyToManyField(to="movies_app.actor")),
            ],
        ),
    ]
